import test from 'node:test';
import assert from 'node:assert/strict';
import {cloudTrialPlan,readCloudTrialConfig,probeExistingQqBot} from '../src/cloud-trial.js';
const config=()=>readCloudTrialConfig({QQ_APP_ID:'fixture-existing-bot',QQ_BOT_SECRET:'fixture-not-a-secret',QQ_API_PROFILE:'tencent-sdk'});
function transport({url='wss://api.sgroup.qq.com/websocket?token=fixture-sensitive',remaining=1,fail,afterToken}={}){const calls=[];return {calls,async send(target,options){options.beforeConnect?.();calls.push({target,options});if(fail)return {status:fail,body:Buffer.from('{"raw":"must-not-leak"}')};if(calls.length===1){afterToken?.();return {status:200,body:Buffer.from('{"access_token":"fixture-sensitive-token","expires_in":7200}')};}return {status:200,body:Buffer.from(JSON.stringify({url,session_start_limit:{remaining,reset_after:10000}}))};}};}
test('plan does not read configuration or promise scan/current-dot connection',()=>{const plan=cloudTrialPlan();assert.equal(plan.credentials_read,false);assert.equal(plan.scan_available,true);assert.equal(plan.current_dot_connected,false);assert.equal(plan.maximum_requests,2);});
test('diagnostic authorization and credential shape are required before any network',async()=>{const t=transport();await assert.rejects(probeExistingQqBot(config(),{send:t.send}));assert.equal(t.calls.length,0);for(const env of [{},{QQ_APP_ID:'fixture',QQ_BOT_SECRET:'short'},{QQ_APP_ID:'fixture',QQ_BOT_SECRET:'secret\nvalue'}])assert.throws(()=>readCloudTrialConfig(env));});
test('existing bot probe uses exactly token plus Gateway discovery, never receives or replies',async()=>{const t=transport();const result=await probeExistingQqBot(config(),{approved:true,send:t.send});assert.equal(result.status,'provider_discovery_passed');assert.equal(t.calls.length,2);assert.equal(t.calls[0].target,'https://bots.qq.com/app/getAppAccessToken');assert.equal(t.calls[1].target,'https://api.sgroup.qq.com/gateway/bot');assert.ok(t.calls.every(c=>c.options.purpose==='provider'));assert.equal(result.messages_received,0);assert.equal(result.messages_sent,0);assert.equal(result.live_gateway_connected,false);assert.equal(result.owner_identity_verified,false);assert.equal(result.current_dot_connected,false);for(const value of ['fixture-sensitive','fixture-existing-bot','fixture-not-a-secret','?token='])assert.ok(!JSON.stringify(result).includes(value));});
test('revocation after token blocks Gateway discovery',async()=>{const controller=new AbortController();const t=transport({afterToken:()=>controller.abort()});const r=await probeExistingQqBot(config(),{approved:true,signal:controller.signal,send:t.send});assert.equal(r.status,'cancelled_or_expired');assert.equal(t.calls.length,1);});
test('expiry after token blocks Gateway discovery',async()=>{let now=0;const t=transport({afterToken:()=>now=60001});const r=await probeExistingQqBot(config(),{approved:true,clock:()=>now,send:t.send});assert.equal(r.status,'cancelled_or_expired');assert.equal(t.calls.length,1);});
test('failed official read is not retried, changed to another profile, or leaked',async()=>{const t=transport({fail:401});const r=await probeExistingQqBot(config(),{approved:true,send:t.send});assert.equal(r.status,'provider_check_failed');assert.equal(r.last_http_status,401);assert.equal(t.calls.length,1);assert.ok(!JSON.stringify(r).includes('must-not-leak'));});
test('unapproved WSS host, invalid origin and exhausted quota do not open sockets',async()=>{for(const url of ['wss://attacker.invalid/x','ws://api.sgroup.qq.com/x','wss://api.sgroup.qq.com:444/x','wss://user:secret@api.sgroup.qq.com/x']){const t=transport({url});const r=await probeExistingQqBot(config(),{approved:true,send:t.send});assert.notEqual(r.status,'provider_discovery_passed');assert.equal(r.live_gateway_connected,false);}const t=transport({remaining:0});const r=await probeExistingQqBot(config(),{approved:true,send:t.send});assert.equal(r.gateway_quota_available,false);assert.equal(r.live_gateway_connected,false);});
test('separate sandbox selection stays on sandbox Gateway with no production fallback',async()=>{const selected=readCloudTrialConfig({QQ_APP_ID:'fixture',QQ_BOT_SECRET:'fixture-secret',QQ_API_PROFILE:'tencent-sandbox'});const t=transport({url:'wss://sandbox.api.sgroup.qq.com/x'});const r=await probeExistingQqBot(selected,{approved:true,send:t.send});assert.equal(r.status,'provider_discovery_passed');assert.equal(t.calls[1].target,'https://sandbox.api.sgroup.qq.com/gateway/bot');});
